# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csci5253_finalProject/gRPC/final.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&csci5253_finalProject/gRPC/final.proto\x12\x05\x66inal\"\x1e\n\x0e\x63onvertRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"\x1c\n\x0c\x63onvertReply\x12\x0c\n\x04hash\x18\x01 \x01(\t\"\x0e\n\x0cqueueRequest\"\x1a\n\nqueueReply\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\"\x1d\n\rdeleteRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\"\x1d\n\x0b\x64\x65leteReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1f\n\x0f\x64ownloadRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\"\x1d\n\rdownloadReply\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x32\xe3\x01\n\x07project\x12\x37\n\tdoconvert\x12\x15.final.convertRequest\x1a\x13.final.convertReply\x12/\n\x05queue\x12\x13.final.queueRequest\x1a\x11.final.queueReply\x12\x32\n\x06\x64\x65lete\x12\x14.final.deleteRequest\x1a\x12.final.deleteReply\x12:\n\ndoDownload\x12\x16.final.downloadRequest\x1a\x14.final.downloadReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csci5253_finalProject.gRPC.final_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONVERTREQUEST._serialized_start=49
  _CONVERTREQUEST._serialized_end=79
  _CONVERTREPLY._serialized_start=81
  _CONVERTREPLY._serialized_end=109
  _QUEUEREQUEST._serialized_start=111
  _QUEUEREQUEST._serialized_end=125
  _QUEUEREPLY._serialized_start=127
  _QUEUEREPLY._serialized_end=153
  _DELETEREQUEST._serialized_start=155
  _DELETEREQUEST._serialized_end=184
  _DELETEREPLY._serialized_start=186
  _DELETEREPLY._serialized_end=215
  _DOWNLOADREQUEST._serialized_start=217
  _DOWNLOADREQUEST._serialized_end=248
  _DOWNLOADREPLY._serialized_start=250
  _DOWNLOADREPLY._serialized_end=279
  _PROJECT._serialized_start=282
  _PROJECT._serialized_end=509
# @@protoc_insertion_point(module_scope)
