# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import final_pb2 as final__pb2


class lab6Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.doconvert = channel.unary_unary(
                '/final.lab6/doconvert',
                request_serializer=final__pb2.convertRequest.SerializeToString,
                response_deserializer=final__pb2.convertReply.FromString,
                )
        self.queue = channel.unary_unary(
                '/final.lab6/queue',
                request_serializer=final__pb2.queueRequest.SerializeToString,
                response_deserializer=final__pb2.queueReply.FromString,
                )
        self.delete = channel.unary_unary(
                '/final.lab6/delete',
                request_serializer=final__pb2.deleteRequest.SerializeToString,
                response_deserializer=final__pb2.deleteReply.FromString,
                )
        self.doDownload = channel.unary_unary(
                '/final.lab6/doDownload',
                request_serializer=final__pb2.downloadRequest.SerializeToString,
                response_deserializer=final__pb2.downloadReply.FromString,
                )


class lab6Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def doconvert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_lab6Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'doconvert': grpc.unary_unary_rpc_method_handler(
                    servicer.doconvert,
                    request_deserializer=final__pb2.convertRequest.FromString,
                    response_serializer=final__pb2.convertReply.SerializeToString,
            ),
            'queue': grpc.unary_unary_rpc_method_handler(
                    servicer.queue,
                    request_deserializer=final__pb2.queueRequest.FromString,
                    response_serializer=final__pb2.queueReply.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=final__pb2.deleteRequest.FromString,
                    response_serializer=final__pb2.deleteReply.SerializeToString,
            ),
            'doDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.doDownload,
                    request_deserializer=final__pb2.downloadRequest.FromString,
                    response_serializer=final__pb2.downloadReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'final.lab6', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class lab6(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def doconvert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/final.lab6/doconvert',
            final__pb2.convertRequest.SerializeToString,
            final__pb2.convertReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/final.lab6/queue',
            final__pb2.queueRequest.SerializeToString,
            final__pb2.queueReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/final.lab6/delete',
            final__pb2.deleteRequest.SerializeToString,
            final__pb2.deleteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def doDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/final.lab6/doDownload',
            final__pb2.downloadRequest.SerializeToString,
            final__pb2.downloadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
